<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SignAssembly>True</SignAssembly>
    <Title>HwHash - HWInfo data to Dictionary</Title>
    <Authors>Dante Wackermann,DLain</Authors>
    <Description>HwHash is a static class that grabs HWInfo sensor information and saves it to a Dictionary so it can be easily read and upload to InfluxDB or any other application you may deem useful.</Description>
    <RepositoryType>git</RepositoryType>
    <PackageTags>hwhash,hwinfo,hwinfo dictionary,hwinfo shared memory, metrics, hardware metrics,</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RepositoryUrl>https://github.com/layer07/HWHash</RepositoryUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageIcon></PackageIcon>
    <PackageProjectUrl>https://kernelriot.com</PackageProjectUrl>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Version>2.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">True</GeneratePackageOnBuild>
    <NoWarn>1701;1702;IDE0063;IDE0290</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="..\media\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="..\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>